# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\lgy\pyqt\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widgetL = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetL.sizePolicy().hasHeightForWidth())
        self.widgetL.setSizePolicy(sizePolicy)
        self.widgetL.setObjectName("widgetL")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widgetL)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.splitter_2 = QtWidgets.QSplitter(self.widgetL)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.widget_2 = QtWidgets.QWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonTrain = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButtonTrain.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/训练集.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("src/训练集s.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButtonTrain.setIcon(icon)
        self.pushButtonTrain.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonTrain.setCheckable(True)
        self.pushButtonTrain.setChecked(True)
        self.pushButtonTrain.setObjectName("pushButtonTrain")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pushButtonTrain)
        self.horizontalLayout_3.addWidget(self.pushButtonTrain)
        self.pushButtonTest = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setKerning(True)
        self.pushButtonTest.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/测试集.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("src/测试集s.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButtonTest.setIcon(icon1)
        self.pushButtonTest.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonTest.setCheckable(True)
        self.pushButtonTest.setObjectName("pushButtonTest")
        self.buttonGroup.addButton(self.pushButtonTest)
        self.horizontalLayout_3.addWidget(self.pushButtonTest)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButton_addimage = QtWidgets.QToolButton(self.widget_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("src/添加图片.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_addimage.setIcon(icon2)
        self.toolButton_addimage.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_addimage.setObjectName("toolButton_addimage")
        self.horizontalLayout_2.addWidget(self.toolButton_addimage)
        self.toolButton_addfolder = QtWidgets.QToolButton(self.widget_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("src/添加文件夹.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_addfolder.setIcon(icon3)
        self.toolButton_addfolder.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_addfolder.setObjectName("toolButton_addfolder")
        self.horizontalLayout_2.addWidget(self.toolButton_addfolder)
        self.toolButton_moveToOppo = QtWidgets.QToolButton(self.widget_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("src/移动到组.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_moveToOppo.setIcon(icon4)
        self.toolButton_moveToOppo.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_moveToOppo.setObjectName("toolButton_moveToOppo")
        self.horizontalLayout_2.addWidget(self.toolButton_moveToOppo)
        self.toolButton_deleteimage = QtWidgets.QToolButton(self.widget_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("src/删除.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_deleteimage.setIcon(icon5)
        self.toolButton_deleteimage.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_deleteimage.setObjectName("toolButton_deleteimage")
        self.horizontalLayout_2.addWidget(self.toolButton_deleteimage)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.picNum = QtWidgets.QLabel(self.widget_2)
        self.picNum.setObjectName("picNum")
        self.horizontalLayout_2.addWidget(self.picNum)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageTrain = QtWidgets.QWidget()
        self.pageTrain.setObjectName("pageTrain")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageTrain)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableTrain = QtWidgets.QTableView(self.pageTrain)
        self.tableTrain.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableTrain.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableTrain.setObjectName("tableTrain")
        self.tableTrain.horizontalHeader().setVisible(True)
        self.tableTrain.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tableTrain)
        self.stackedWidget.addWidget(self.pageTrain)
        self.pageTest = QtWidgets.QWidget()
        self.pageTest.setObjectName("pageTest")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pageTest)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableTest = QtWidgets.QTableView(self.pageTest)
        self.tableTest.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableTest.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableTest.setObjectName("tableTest")
        self.tableTest.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.tableTest)
        self.stackedWidget.addWidget(self.pageTest)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.widget = QtWidgets.QWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButton_addclass = QtWidgets.QToolButton(self.widget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("src/添加.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_addclass.setIcon(icon6)
        self.toolButton_addclass.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_addclass.setObjectName("toolButton_addclass")
        self.horizontalLayout_4.addWidget(self.toolButton_addclass)
        self.toolButton_deleteclass = QtWidgets.QToolButton(self.widget)
        self.toolButton_deleteclass.setIcon(icon5)
        self.toolButton_deleteclass.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_deleteclass.setObjectName("toolButton_deleteclass")
        self.horizontalLayout_4.addWidget(self.toolButton_deleteclass)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.catNum = QtWidgets.QLabel(self.widget)
        self.catNum.setObjectName("catNum")
        self.horizontalLayout_4.addWidget(self.catNum)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tableCat = QtWidgets.QTableView(self.widget)
        self.tableCat.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableCat.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableCat.setObjectName("tableCat")
        self.tableCat.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableCat)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_7.addWidget(self.splitter_2)
        self.widgetR = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetR.sizePolicy().hasHeightForWidth())
        self.widgetR.setSizePolicy(sizePolicy)
        self.widgetR.setObjectName("widgetR")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widgetR)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.splitter_3 = QtWidgets.QSplitter(self.widgetR)
        self.splitter_3.setAutoFillBackground(False)
        self.splitter_3.setLineWidth(1)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.widget_4 = QtWidgets.QWidget(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.picShow = QtWidgets.QGraphicsView(self.widget_4)
        self.picShow.setObjectName("picShow")
        self.verticalLayout_8.addWidget(self.picShow)
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toolButton_showlabel = QtWidgets.QToolButton(self.widget_3)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("src/标记.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_showlabel.setIcon(icon7)
        self.toolButton_showlabel.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_showlabel.setObjectName("toolButton_showlabel")
        self.horizontalLayout_5.addWidget(self.toolButton_showlabel)
        self.toolButton_showdetect = QtWidgets.QToolButton(self.widget_3)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("src/检测-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_showdetect.setIcon(icon8)
        self.toolButton_showdetect.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_showdetect.setObjectName("toolButton_showdetect")
        self.horizontalLayout_5.addWidget(self.toolButton_showdetect)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.picSize = QtWidgets.QLabel(self.widget_3)
        self.picSize.setObjectName("picSize")
        self.horizontalLayout_5.addWidget(self.picSize)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.curPos = QtWidgets.QLabel(self.widget_3)
        self.curPos.setOpenExternalLinks(False)
        self.curPos.setObjectName("curPos")
        self.horizontalLayout_5.addWidget(self.curPos)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_8.addWidget(self.widget_3)
        self.widget_5 = QtWidgets.QWidget(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabResult = QtWidgets.QWidget()
        self.tabResult.setObjectName("tabResult")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tabResult)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_7 = QtWidgets.QWidget(self.tabResult)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.splitter_4 = QtWidgets.QSplitter(self.widget_7)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toolButton_modelinfo = QtWidgets.QToolButton(self.layoutWidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("src/详细信息.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_modelinfo.setIcon(icon9)
        self.toolButton_modelinfo.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_modelinfo.setObjectName("toolButton_modelinfo")
        self.horizontalLayout_6.addWidget(self.toolButton_modelinfo)
        self.toolButton_modelimport = QtWidgets.QToolButton(self.layoutWidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("src/导入.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_modelimport.setIcon(icon10)
        self.toolButton_modelimport.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_modelimport.setObjectName("toolButton_modelimport")
        self.horizontalLayout_6.addWidget(self.toolButton_modelimport)
        self.toolButton_modelexport = QtWidgets.QToolButton(self.layoutWidget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("src/导出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_modelexport.setIcon(icon11)
        self.toolButton_modelexport.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_modelexport.setObjectName("toolButton_modelexport")
        self.horizontalLayout_6.addWidget(self.toolButton_modelexport)
        self.toolButton_modeldelete = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_modeldelete.setIcon(icon5)
        self.toolButton_modeldelete.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_modeldelete.setObjectName("toolButton_modeldelete")
        self.horizontalLayout_6.addWidget(self.toolButton_modeldelete)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.modelNum = QtWidgets.QLabel(self.layoutWidget)
        self.modelNum.setObjectName("modelNum")
        self.horizontalLayout_6.addWidget(self.modelNum)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.tableView_modelResult = QtWidgets.QTableView(self.layoutWidget)
        self.tableView_modelResult.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView_modelResult.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_modelResult.setObjectName("tableView_modelResult")
        self.verticalLayout_12.addWidget(self.tableView_modelResult)
        self.tableView_2 = QtWidgets.QTableView(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_2.sizePolicy().hasHeightForWidth())
        self.tableView_2.setSizePolicy(sizePolicy)
        self.tableView_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_2.setObjectName("tableView_2")
        self.tableView_2.verticalHeader().setVisible(False)
        self.horizontalLayout_8.addWidget(self.splitter_4)
        self.horizontalLayout_9.addWidget(self.widget_7)
        self.tabWidget.addTab(self.tabResult, "")
        self.tabTraining = QtWidgets.QWidget()
        self.tabTraining.setObjectName("tabTraining")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tabTraining)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_6 = QtWidgets.QWidget(self.tabTraining)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_13.addWidget(self.widget_6)
        self.tabWidget.addTab(self.tabTraining, "")
        self.verticalLayout_10.addWidget(self.tabWidget)
        self.progressBar = QtWidgets.QProgressBar(self.widget_5)
        self.progressBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.progressBar.setProperty("value", 25)
        self.progressBar.setTextVisible(True)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_10.addWidget(self.progressBar)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.verticalLayout_9.addWidget(self.splitter_3)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setCheckable(False)
        self.actionnew.setChecked(False)
        self.actionnew.setEnabled(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("src/新建.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionnew.setIcon(icon12)
        self.actionnew.setObjectName("actionnew")
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setCheckable(False)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("src/打开.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionopen.setIcon(icon13)
        self.actionopen.setVisible(True)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setCheckable(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("src/保存.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsave.setIcon(icon14)
        self.actionsave.setObjectName("actionsave")
        self.actionSelect = QtWidgets.QAction(MainWindow)
        self.actionSelect.setCheckable(False)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("src/选定.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon15.addPixmap(QtGui.QPixmap("src/选定s.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.actionSelect.setIcon(icon15)
        self.actionSelect.setAutoRepeat(True)
        self.actionSelect.setObjectName("actionSelect")
        self.actionMove = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("src/移动.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon16.addPixmap(QtGui.QPixmap("src/移动s.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.actionMove.setIcon(icon16)
        self.actionMove.setObjectName("actionMove")
        self.actionLine = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("src/直线.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLine.setIcon(icon17)
        self.actionLine.setObjectName("actionLine")
        self.actionPolyLine = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("src/曲线.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPolyLine.setIcon(icon18)
        self.actionPolyLine.setObjectName("actionPolyLine")
        self.actionRect = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("src/矩形.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRect.setIcon(icon19)
        self.actionRect.setObjectName("actionRect")
        self.actionElli = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("src/椭圆.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionElli.setIcon(icon20)
        self.actionElli.setObjectName("actionElli")
        self.actionPolygon = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("src/多边形.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPolygon.setIcon(icon21)
        self.actionPolygon.setObjectName("actionPolygon")
        self.actionSpace = QtWidgets.QAction(MainWindow)
        self.actionSpace.setText("")
        self.actionSpace.setObjectName("actionSpace")
        self.actionTrain = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("src/训练.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTrain.setIcon(icon22)
        self.actionTrain.setObjectName("actionTrain")
        self.actionTest = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("src/检测.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTest.setIcon(icon23)
        self.actionTest.setObjectName("actionTest")
        self.toolBar.addAction(self.actionnew)
        self.toolBar.addAction(self.actionopen)
        self.toolBar.addAction(self.actionsave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSelect)
        self.toolBar.addAction(self.actionMove)
        self.toolBar.addAction(self.actionLine)
        self.toolBar.addAction(self.actionPolyLine)
        self.toolBar.addAction(self.actionRect)
        self.toolBar.addAction(self.actionElli)
        self.toolBar.addAction(self.actionPolygon)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSpace)
        self.toolBar.addAction(self.actionTrain)
        self.toolBar.addAction(self.actionTest)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionnew.triggered.connect(MainWindow.slot_new)
        self.actionopen.triggered.connect(MainWindow.slot_open)
        self.actionsave.triggered.connect(MainWindow.slot_save)
        self.actionSelect.triggered.connect(MainWindow.slot_select)
        self.actionMove.triggered.connect(MainWindow.slot_move)
        self.actionLine.triggered.connect(MainWindow.slot_line)
        self.actionPolyLine.triggered.connect(MainWindow.slot_polyline)
        self.actionRect.triggered.connect(MainWindow.slot_rect)
        self.actionElli.triggered.connect(MainWindow.slot_elli)
        self.actionPolygon.triggered.connect(MainWindow.slot_polygon)
        self.actionTrain.triggered.connect(MainWindow.slot_train)
        self.actionTest.triggered.connect(MainWindow.slot_test)
        self.pushButtonTrain.clicked.connect(MainWindow.slot_traindata)
        self.pushButtonTest.clicked.connect(MainWindow.slot_testdata)
        self.toolButton_addimage.clicked.connect(MainWindow.slot_addimage)
        self.toolButton_addfolder.clicked.connect(MainWindow.slot_addFolder)
        self.toolButton_moveToOppo.clicked.connect(MainWindow.slot_moveToOpposite)
        self.toolButton_deleteimage.clicked.connect(MainWindow.slot_deleteimage)
        self.toolButton_addclass.clicked.connect(MainWindow.slot_addClass)
        self.toolButton_deleteclass.clicked.connect(MainWindow.slot_deleteClass)
        self.toolButton_modelinfo.clicked.connect(MainWindow.slot_modelInfo)
        self.toolButton_modelimport.clicked.connect(MainWindow.slot_importModel)
        self.toolButton_modelexport.clicked.connect(MainWindow.slot_exportModel)
        self.toolButton_modeldelete.clicked.connect(MainWindow.slot_deleteModel)
        self.toolButton_showlabel.clicked.connect(MainWindow.slot_showLabel)
        self.toolButton_showdetect.clicked.connect(MainWindow.slot_showDetect)
        self.tableTrain.clicked['QModelIndex'].connect(MainWindow.slot_picChange)
        self.tableTest.clicked['QModelIndex'].connect(MainWindow.slot_picChange)
        self.tableCat.clicked['QModelIndex'].connect(MainWindow.slot_selectCat)
        self.tableCat.doubleClicked['QModelIndex'].connect(MainWindow.slot_editCat)
        self.tableView_modelResult.clicked['QModelIndex'].connect(MainWindow.slot_selectModel)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonTrain.setText(_translate("MainWindow", "训练集"))
        self.pushButtonTest.setText(_translate("MainWindow", "测试集"))
        self.toolButton_addimage.setText(_translate("MainWindow", "..."))
        self.toolButton_addfolder.setText(_translate("MainWindow", "..."))
        self.toolButton_moveToOppo.setText(_translate("MainWindow", "..."))
        self.toolButton_deleteimage.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "图片数："))
        self.picNum.setText(_translate("MainWindow", "0"))
        self.toolButton_addclass.setText(_translate("MainWindow", "..."))
        self.toolButton_deleteclass.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "类别总数："))
        self.catNum.setText(_translate("MainWindow", "0"))
        self.toolButton_showlabel.setText(_translate("MainWindow", "..."))
        self.toolButton_showdetect.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "图像尺寸："))
        self.picSize.setText(_translate("MainWindow", "0*0"))
        self.label.setText(_translate("MainWindow", "当前坐标："))
        self.curPos.setText(_translate("MainWindow", "0,0"))
        self.toolButton_modelinfo.setToolTip(_translate("MainWindow", "详细信息"))
        self.toolButton_modelinfo.setText(_translate("MainWindow", "..."))
        self.toolButton_modelimport.setToolTip(_translate("MainWindow", "导入模型"))
        self.toolButton_modelimport.setText(_translate("MainWindow", "..."))
        self.toolButton_modelexport.setToolTip(_translate("MainWindow", "导出模型"))
        self.toolButton_modelexport.setText(_translate("MainWindow", "..."))
        self.toolButton_modeldelete.setToolTip(_translate("MainWindow", "删除模型"))
        self.toolButton_modeldelete.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "模型总数："))
        self.modelNum.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabResult), _translate("MainWindow", "模型结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTraining), _translate("MainWindow", "训练中"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionnew.setText(_translate("MainWindow", "新建"))
        self.actionnew.setToolTip(_translate("MainWindow", "新建"))
        self.actionopen.setText(_translate("MainWindow", "打开"))
        self.actionopen.setToolTip(_translate("MainWindow", "打开"))
        self.actionsave.setText(_translate("MainWindow", "保存"))
        self.actionsave.setToolTip(_translate("MainWindow", "保存"))
        self.actionSelect.setText(_translate("MainWindow", "选定"))
        self.actionSelect.setToolTip(_translate("MainWindow", "选定"))
        self.actionMove.setText(_translate("MainWindow", "移动"))
        self.actionMove.setToolTip(_translate("MainWindow", "移动"))
        self.actionLine.setText(_translate("MainWindow", "直线"))
        self.actionLine.setToolTip(_translate("MainWindow", "直线"))
        self.actionPolyLine.setText(_translate("MainWindow", "曲线"))
        self.actionPolyLine.setToolTip(_translate("MainWindow", "曲线"))
        self.actionRect.setText(_translate("MainWindow", "矩形"))
        self.actionRect.setToolTip(_translate("MainWindow", "矩形"))
        self.actionElli.setText(_translate("MainWindow", "椭圆"))
        self.actionElli.setToolTip(_translate("MainWindow", "椭圆"))
        self.actionPolygon.setText(_translate("MainWindow", "多边行"))
        self.actionPolygon.setToolTip(_translate("MainWindow", "多边形"))
        self.actionTrain.setText(_translate("MainWindow", "训练"))
        self.actionTrain.setToolTip(_translate("MainWindow", "训练"))
        self.actionTest.setText(_translate("MainWindow", "检测"))
        self.actionTest.setToolTip(_translate("MainWindow", "检测"))

